# Generated by Django 3.2.25 on 2024-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='main.Image'),
        ),
    ]
