# Generated by Django 3.2.25 on 2024-10-05 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_capsule_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='creating',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='capsules', to='main.Image'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='capsules', to=settings.AUTH_USER_MODEL),
        ),
    ]
