# Generated by Django 3.2.25 on 2025-12-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20241005_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_github_token',
            },
        ),
    ]
