# Generated by Django 3.2.25 on 2025-12-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_githubtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'db_table': 'main_language',
                'ordering': ['name'],
            },
        ),
    ]
