# Generated by Django 3.2.25 on 2025-12-06 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('stargazers_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_user_repository',
                'ordering': ['-pushed_at'],
                'unique_together': {('user', 'github_id')},
            },
        ),
    ]
