# Generated by Django 3.2.25 on 2025-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
